export const API_URL = 'http://127.0.0.1:5000';

export const FETCH_ROOMS_REQUEST = 'FETCH_ROOMS_REQUEST';
export const FETCH_ROOMS_SUCCESS ='FETCH_ROOMS_SUCCESS';
export const FETCH_ROOMS_ERROR = 'FETCH_ROOMS_ERROR';

export const FETCH_ROOM_USERS_REQUEST = 'FETCH_ROOM_USERS_REQUEST';
export const FETCH_ROOM_USERS_SUCCESS ='FETCH_ROOM_USERS_SUCCESS';
export const FETCH_ROOM_USERS_ERROR = 'FETCH_ROOM_USERS_ERROR';

export const ADD_ROOM_USERS_REQUEST = 'ADD_ROOM_USERS_REQUEST';
export const ADD_ROOM_USERS_SUCCESS ='ADD_ROOM_USERS_SUCCESS';
export const ADD_ROOM_USERS_ERROR = 'ADD_ROOM_USERS_ERROR';